const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const vm = require('node:vm')
function load(name, imports = {}) {
  const context = vm.createContext(imports)
  const source = fs.readFileSync(path.join(__dirname, '..', name), 'utf8')
    .replace(/^\.(?:pragma|import).*$/gm, '')
  vm.runInContext(source, context)
  return context
}
const Icons = load('GroupIcons.js', {Lucide: load('LucideIcons.js')})
assert(Icons.names.length > 1800)
assert.deepEqual(Array.from(Icons.names.slice(0, 9)), ['windows', 'development', 'input', 'sound', 'devices', 'display', 'appearance', 'maintenance', 'group'])
assert.equal(Icons.search(' ROCKET ')[0], 'rocket')
assert(Icons.search('wireless').includes('wifi'))
assert.equal(Icons.search('no-such-icon-zzzz').length, 0)
assert(Icons.names.includes('windows'))
assert(!Icons.names.includes('manager'))
assert.equal(new Set(Icons.names).size, Icons.names.length)
const svg = decodeURIComponent(Icons.source('rocket', '#ffffff').split(',')[1])
assert(svg.includes('<path'))
assert(svg.includes('stroke="#ffffff"'))
assert.equal(Icons.source('unknown-name', '#fff'), Icons.source('group', '#fff'))
console.log('icon catalog, keyword search, legacy names and fallback passed')
