#!/usr/bin/env -S uv run --no-project python
"""Regenerate the offline Lucide catalog from a pinned upstream revision."""
import io
import json
from pathlib import Path
import re
import tarfile
import urllib.request

REVISION = '2bfb9bb1bae5d74f6a9f81640ddd8bccc2c71860'
ROOT = Path(__file__).resolve().parent.parent
url = f'https://codeload.github.com/lucide-icons/lucide/tar.gz/{REVISION}'
with urllib.request.urlopen(url, timeout=120) as response:
    archive = tarfile.open(fileobj=io.BytesIO(response.read()), mode='r:gz')
paths, terms = {}, {}
for member in archive.getmembers():
    parts = Path(member.name).parts
    if not member.isfile():
        continue
    if len(parts) == 2 and parts[-1] == 'LICENSE':
        (ROOT / 'assets/LICENSE-lucide.txt').write_bytes(archive.extractfile(member).read())
    if len(parts) != 3 or parts[1] != 'icons':
        continue
    data = archive.extractfile(member).read().decode()
    name = Path(parts[-1]).stem
    if parts[-1].endswith('.svg'):
        match = re.search(r'<svg\b[^>]*>(.*?)</svg>', data, re.S)
        if not match:
            raise ValueError(f'Invalid icon: {name}')
        paths[name] = re.sub(r'\s+', ' ', match[1]).strip()
    elif parts[-1].endswith('.json'):
        meta = json.loads(data)
        terms[name] = ' '.join(meta.get('tags', []) + meta.get('categories', []))
output = '.pragma library\n\n// Lucide Icons, ISC/MIT. See assets/LICENSE-lucide.txt.\n'
output += f'// Source revision: {REVISION}. Generated by scripts/update-icons.py.\n'
output += 'var paths = ' + json.dumps(dict(sorted(paths.items())), ensure_ascii=False, indent=2) + '\n\n'
output += 'var keywords = ' + json.dumps({k: terms.get(k, '') for k in sorted(paths)}, ensure_ascii=False, indent=2) + '\n'
(ROOT / 'LucideIcons.js').write_text(output)
print(f'Bundled {len(paths)} icons with search keywords.')
